- secret:
    name: test_secret
    data:
      password: !encrypted/pkcs1-oaep
        - GUOFaqG8d7OZlrlnbdI6ODfU2AnYWlrJ5tsPNxPz+qPyb6eOFvZs4CoUfjcEojRUSCXva
          N1FBRxQJ6syMkXGrVUGFQwUQ+OJimZIJW5zzmhRWnbrCohHQ5qpL9Xhx2BB7DUcctb27A
          c7JmoY7e62/HWPTCizNZZjWP85DqM9i42LYJKBgPrGRBi5v+ZMgH4qwawgt7f9etVWxXV
          uC0fWUJ6S2snUVdarW/5drw7ThL+KLEl1cKBWFDznWyI9PhNWL9tM91dcJ1xBsHmSA3h9
          Y+iboSC5HleMcP+qS8Z0ErSWZVwH4jhnh0VqcC5tzlkGdneNOQPAr5Qu13FVhblzybJkt
          eX0y1WbmMYXkJVx3j5Wxhrzr46URU82fCYZlsGU+w56+fDRb5iLw9VV+QfAKuRcXqf4tk
          jVOisVTx721AbQ83+K9JhFYfXuTrXiv1OKLxWrjBlPTlQTGsqstSATIukOi6ILWu/b/Pj
          LaoccvH9Pz7VVVJiINdwnvsCKbgL/88B9Qlh7u8Yghmvt/aUTCZlHBcr1cTV1HshZKm7i
          4lk6+6VWZeyX30vQqQGfJUNg6A5QeOeMlg3pQjduyAcFdnkbEd2f2t2QLsou+BrB612R4
          VfYul+X37yPB3eQZt5htH9IvXeU+sy3x3q0ZcMVJaZkf0fIqfrWdvpUGkfXg0Q=

- job:
    name: tox-functional-secrets
    parent: tox-functional
    secrets:
      - name: test
        secret: test_secret
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    templates:
      - publish-to-pypi
    check:
      jobs:
        - tox-py37
        - tox-py38
        - tox-pep8
        - tox-docs
        - tox-functional-secrets
    gate:
      jobs:
        - tox-py37
        - tox-py38
        - tox-pep8
        - tox-docs
        - tox-functional-secrets
    periodic:
      jobs:
        - tox-functional-secrets
